[
    {
        "domain": ".grammarly.com",
        "expirationDate": 1653372651,
        "hostOnly": false,
        "httpOnly": false,
        "name": "grauth",
        "path": "/",
        "sameSite": null,
        "secure": false,
        "session": false,
        "storeId": null,
        "value": "AABKv4Ddc0VpbmY_AizeGLABe122jk0SROMFau-5DogIcLv7uSDJD28ZXhaGnS5MXoKky4vI9FnKQ9U_"
    },
    {
        "domain": ".grammarly.com",
        "expirationDate": 1653307947.406041,
        "hostOnly": false,
        "httpOnly": true,
        "name": "redirect_location",
        "path": "/",
        "sameSite": null,
        "secure": true,
        "session": false,
        "storeId": null,
        "value": "eyJ0eXBlIjoiIiwibG9jYXRpb24iOiJodHRwczovL2FwcC5ncmFtbWFybHkuY29tLyJ9"
    },
    {
        "domain": ".grammarly.com",
        "expirationDate": 1668856350.808221,
        "hostOnly": false,
        "httpOnly": false,
        "name": "experiment_groups",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": null,
        "value": "fsrw_in_sidebar_allusers_enabled|extension_assistant_bundles_all_consumers_enabled|fsrw_in_assistant_all_consumers_enabled|extension_new_rich_text_fields_enabled|gdocs_for_chrome_enabled|officeaddin_outcomes_ui_exp5_enabled1|completions_beta_enabled|premium_ungating_renewal_notification_enabled|kaza_security_hub_enabled|quarantine_messages_enabled|small_hover_menus_existing_enabled|gb_snippets_csv_upload_enabled|grammarly_web_ukraine_logo_dapi_enabled|officeaddin_upgrade_state_exp2_enabled1|gb_in_editor_premium_Test1|gb_analytics_mvp_phase_one_enabled|wonderpass_enabled|apply_formatting_all_consumers_enabled|ipm_extension_release_test_1|attention_score_card_premium_no_iid_enabled|snippets_in_ws_gate_enabled|extension_assistant_experiment_all_consumers_enabled|extension_assistant_bundles_all_enabled|officeaddin_proofit_exp3_enabled|gdocs_for_all_firefox_enabled|shared_workspaces_enabled|gb_analytics_mvp_phase_one_30_day_enabled|auto_complete_correct_safari_enabled|fluid_gdocs_rollout_enabled|officeaddin_ue_exp3_enabled|officeaddin_upgrade_state_exp1_enabled1|safari_migration_inline_disabled_enabled|completions_release_enabled1|extension_assistant_all_consumers_enabled|fsrw_in_assistant_all_enabled|autocorrect_new_ui_v3|emogenie_beta_enabled|apply_formatting_all_enabled|shadow_dom_chrome_enabled|extension_assistant_experiment_all_enabled|gdocs_for_all_safari_enabled|extension_assistant_all_enabled|safari_migration_backup_notif1_enabled|auto_complete_correct_edge_enabled|takeaways_premium_enabled|safari_migration_popup_editor_disabled_enabled|extension_check_manakin_v2_experiment_enabled|safari_migration_inline_warning_enabled|gdocs_new_mapping_enabled|officeaddin_perf_exp3_enabled|officeaddin_muted_alerts_exp2_enabled1"
    },
    {
        "domain": ".grammarly.com",
        "expirationDate": 1968905287,
        "hostOnly": false,
        "httpOnly": false,
        "name": "ga_clientId",
        "path": "/",
        "sameSite": null,
        "secure": false,
        "session": false,
        "storeId": null,
        "value": "1768971474.1647316228"
    },
    {
        "domain": ".grammarly.com",
        "expirationDate": 1653372651,
        "hostOnly": false,
        "httpOnly": false,
        "name": "csrf-token",
        "path": "/",
        "sameSite": null,
        "secure": false,
        "session": false,
        "storeId": null,
        "value": "AABKv2DF4gsNnJoenKTMN9cFqPrmSg7WkNNJeg"
    },
    {
        "domain": ".grammarly.com",
        "expirationDate": 1653307947.406146,
        "hostOnly": false,
        "httpOnly": false,
        "name": "browser_info",
        "path": "/",
        "sameSite": null,
        "secure": false,
        "session": false,
        "storeId": null,
        "value": "CHROME:101:COMPUTER:SUPPORTED:FREEMIUM:WINDOWS_10:WINDOWS"
    },
    {
        "domain": ".grammarly.com",
        "expirationDate": 1653412347.406127,
        "hostOnly": false,
        "httpOnly": false,
        "name": "funnelType",
        "path": "/",
        "sameSite": null,
        "secure": false,
        "session": false,
        "storeId": null,
        "value": "free"
    },
    {
        "domain": ".grammarly.com",
        "expirationDate": 1968745949.086,
        "hostOnly": false,
        "httpOnly": false,
        "name": "gnar_containerId",
        "path": "/",
        "sameSite": null,
        "secure": false,
        "session": false,
        "storeId": null,
        "value": "nuwp6udq0r600ro2"
    },
    {
        "domain": ".grammarly.com",
        "expirationDate": 1668838244,
        "hostOnly": false,
        "httpOnly": false,
        "name": "OptanonConsent",
        "path": "/",
        "sameSite": "lax",
        "secure": false,
        "session": false,
        "storeId": null,
        "value": "isIABGlobal=false&datestamp=Sun+May+22+2022+23%3A10%3A44+GMT-0700+(Pacific+Daylight+Time)&version=6.34.0&hosts=&consentId=cc4dcf44-dae0-4077-b9bb-f5d5bca9e265&interactionCount=1&landingPath=https%3A%2F%2Fwww.grammarly.com%2Fsignin&groups=C0001%3A1%2CC0002%3A0%2CC0003%3A0%2CC0004%3A0"
    },
    {
        "domain": ".grammarly.com",
        "expirationDate": 1968565545.746287,
        "hostOnly": false,
        "httpOnly": true,
        "name": "tdi",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": null,
        "value": "xektu1y6p3anuxybk"
    }
]
