[
{
"domain": ".semrush.com",
"expirationDate": 1716316477,
"hostOnly": false,
"httpOnly": false,
"name": "_mkto_trk",
"path": "/",
"sameSite": null,
"secure": false,
"session": false,
"storeId": null,
"value": "id:519-IIY-869&token:_mch-semrush.com-1653161034138-34233"
},
{
"domain": ".semrush.com",
"expirationDate": 1653244536,
"hostOnly": false,
"httpOnly": false,
"name": "_dc_gtm_UA-6197637-22",
"path": "/",
"sameSite": null,
"secure": false,
"session": false,
"storeId": null,
"value": "1"
},
{
"domain": ".semrush.com",
"expirationDate": 1684780479.065849,
"hostOnly": false,
"httpOnly": false,
"name": "__insp_targlpt",
"path": "/",
"sameSite": "no_restriction",
"secure": true,
"session": false,
"storeId": null,
"value": "RG9tYWluIE92ZXJ2aWV3OiBHZXQgSW5zdGFudCBEb21haW4gU0VPIEFuYWx5c2lz"
},
{
"domain": ".semrush.com",
"expirationDate": 1684780479.489602,
"hostOnly": false,
"httpOnly": false,
"name": "__insp_norec_sess",
"path": "/",
"sameSite": "no_restriction",
"secure": true,
"session": false,
"storeId": null,
"value": "true"
},
{
"domain": ".semrush.com",
"expirationDate": 1968485253,
"hostOnly": false,
"httpOnly": false,
"name": "ref_code",
"path": "/",
"sameSite": null,
"secure": false,
"session": false,
"storeId": null,
"value": "__default__"
},
{
"domain": ".www.semrush.com",
"expirationDate": 253402257600,
"hostOnly": false,
"httpOnly": false,
"name": "G_ENABLED_IDPS",
"path": "/",
"sameSite": null,
"secure": false,
"session": false,
"storeId": null,
"value": "google"
},
{
"domain": ".semrush.com",
"expirationDate": 1684754081,
"hostOnly": false,
"httpOnly": false,
"name": "_clck",
"path": "/",
"sameSite": null,
"secure": false,
"session": false,
"storeId": null,
"value": "1jb57hb|1|f1o|0"
},
{
"domain": ".semrush.com",
"expirationDate": 1686940478,
"hostOnly": false,
"httpOnly": false,
"name": "_ttp",
"path": "/",
"sameSite": null,
"secure": false,
"session": false,
"storeId": null,
"value": "4970d505-1b4b-4c1b-88c0-301a7fd3a19a"
},
{
"domain": ".semrush.com",
"expirationDate": 1661020475,
"hostOnly": false,
"httpOnly": false,
"name": "_rdt_uuid",
"path": "/",
"sameSite": "strict",
"secure": true,
"session": false,
"storeId": null,
"value": "1653161026155.1073f44e-462a-4938-88c1-091529abd549"
},
{
"domain": ".semrush.com",
"expirationDate": 1716316464,
"hostOnly": false,
"httpOnly": false,
"name": "_ga_HYWKMHR981",
"path": "/",
"sameSite": null,
"secure": false,
"session": false,
"storeId": null,
"value": "GS1.1.1653244455.7.0.1653244455.60"
},
{
"domain": "www.semrush.com",
"expirationDate": 1653304427.317137,
"hostOnly": true,
"httpOnly": true,
"name": "GCLB",
"path": "/",
"sameSite": null,
"secure": false,
"session": false,
"storeId": null,
"value": "CMDh1M6VsfnSrQE"
},
{
"domain": ".semrush.com",
"expirationDate": 1653330882,
"hostOnly": false,
"httpOnly": false,
"name": "_clsk",
"path": "/",
"sameSite": null,
"secure": false,
"session": false,
"storeId": null,
"value": "1bsevaa|1653244482083|1|1|f.clarity.ms/collect"
},
{
"domain": ".semrush.com",
"hostOnly": false,
"httpOnly": false,
"name": "app_center_csrf_token",
"path": "/",
"sameSite": null,
"secure": false,
"session": true,
"storeId": null,
"value": "2b8483ccd4464820a315b85a8cf3467c"
},
{
"domain": ".semrush.com",
"expirationDate": 1686940478,
"hostOnly": false,
"httpOnly": false,
"name": "_tt_enable_cookie",
"path": "/",
"sameSite": null,
"secure": false,
"session": false,
"storeId": null,
"value": "1"
},
{
"domain": ".semrush.com",
"expirationDate": 1968485253,
"hostOnly": false,
"httpOnly": false,
"name": "refer_source",
"path": "/",
"sameSite": null,
"secure": false,
"session": false,
"storeId": null,
"value": "\"\""
},
{
"domain": ".semrush.com",
"expirationDate": 1653330875,
"hostOnly": false,
"httpOnly": false,
"name": "_uetsid",
"path": "/",
"sameSite": null,
"secure": false,
"session": false,
"storeId": null,
"value": "7dc4eb70d75911ecbe56e1d9e9e7de83"
},
{
"domain": ".semrush.com",
"expirationDate": 1968485255,
"hostOnly": false,
"httpOnly": false,
"name": "visit_first",
"path": "/",
"sameSite": null,
"secure": false,
"session": false,
"storeId": null,
"value": "1653125255201"
},
{
"domain": ".semrush.com",
"expirationDate": 1684780479.494258,
"hostOnly": false,
"httpOnly": false,
"name": "__insp_norec_howoften",
"path": "/",
"sameSite": "no_restriction",
"secure": true,
"session": false,
"storeId": null,
"value": "true"
},
{
"domain": ".semrush.com",
"expirationDate": 1686940475,
"hostOnly": false,
"httpOnly": false,
"name": "_uetvid",
"path": "/",
"sameSite": null,
"secure": false,
"session": false,
"storeId": null,
"value": "ab8a4640cdfe11ecbd71d50ffafd5df2"
},
{
"domain": "www.semrush.com",
"expirationDate": 1684697025,
"hostOnly": true,
"httpOnly": false,
"name": "__pdst",
"path": "/",
"sameSite": "strict",
"secure": false,
"session": false,
"storeId": null,
"value": "becfa8a5b6d2475782fa0224bd9767e2"
},
{
"domain": ".semrush.com",
"expirationDate": 1684780479.060662,
"hostOnly": false,
"httpOnly": false,
"name": "__insp_nv",
"path": "/",
"sameSite": "no_restriction",
"secure": true,
"session": false,
"storeId": null,
"value": "true"
},
{
"domain": ".semrush.com",
"expirationDate": 1684780479.058297,
"hostOnly": false,
"httpOnly": false,
"name": "__insp_slim",
"path": "/",
"sameSite": "no_restriction",
"secure": true,
"session": false,
"storeId": null,
"value": "1653244479059"
},
{
"domain": ".semrush.com",
"expirationDate": 1684780479.060069,
"hostOnly": false,
"httpOnly": false,
"name": "__insp_targlpu",
"path": "/",
"sameSite": "no_restriction",
"secure": true,
"session": false,
"storeId": null,
"value": "aHR0cHM6Ly93d3cuc2VtcnVzaC5jb20vYW5hbHl0aWNzL292ZXJ2aWV3Lz9zZWFyY2hUeXBlPWRvbWFpbg%3D%3D"
},
{
"domain": ".semrush.com",
"expirationDate": 1684780479.058898,
"hostOnly": false,
"httpOnly": false,
"name": "__insp_wid",
"path": "/",
"sameSite": "no_restriction",
"secure": true,
"session": false,
"storeId": null,
"value": "1764246400"
},
{
"domain": "www.semrush.com",
"expirationDate": 1655810241,
"hostOnly": true,
"httpOnly": false,
"name": "_ampl",
"path": "/",
"sameSite": "no_restriction",
"secure": true,
"session": false,
"storeId": null,
"value": "DGjuqBd2efqfRoSFqua0V"
},
{
"domain": ".semrush.com",
"expirationDate": 1716316476,
"hostOnly": false,
"httpOnly": false,
"name": "_ga",
"path": "/",
"sameSite": null,
"secure": false,
"session": false,
"storeId": null,
"value": "GA1.2.1907154160.1653125265"
},
{
"domain": ".semrush.com",
"expirationDate": 1660901265,
"hostOnly": false,
"httpOnly": false,
"name": "_gcl_au",
"path": "/",
"sameSite": null,
"secure": false,
"session": false,
"storeId": null,
"value": "1.1.1760238684.1653125265"
},
{
"domain": ".semrush.com",
"expirationDate": 1653330876,
"hostOnly": false,
"httpOnly": false,
"name": "_gid",
"path": "/",
"sameSite": null,
"secure": false,
"session": false,
"storeId": null,
"value": "GA1.2.167217084.1653125266"
},
{
"domain": ".semrush.com",
"expirationDate": 1968604463,
"hostOnly": false,
"httpOnly": false,
"name": "cookiehub",
"path": "/",
"sameSite": "lax",
"secure": false,
"session": false,
"storeId": null,
"value": "eyJhbnN3ZXJlZCI6ZmFsc2UsInByZWNvbnNlbnQiOnRydWUsInJldmlzaW9uIjoxLCJkbnQiOmZhbHNlLCJhbGxvd1NhbGUiOnRydWUsImltcGxpY3QiOnRydWUsInJlZ2lvbiI6IkcwIiwidG9rZW4iOiJ4cjFTdHJRZnhKNUFVTmZ3NDRzT3ZnRlA4djF0NnBQVXVaMDd5bEhSVExJUGZNbno4bHJMdnl3dUM0akw5cE1KIiwidGltZXN0YW1wIjoiMjAyMi0wNS0yMVQwOToyNzo0NC41NDVaIiwiY2F0ZWdvcmllcyI6W3siY2lkIjoxLCJpZCI6Im5lY2Vzc2FyeSIsInZhbHVlIjp0cnVlLCJwcmVjb25zZW50Ijp0cnVlLCJmaXJlZCI6ZmFsc2V9LHsiY2lkIjoyLCJpZCI6InByZWZlcmVuY2VzIiwidmFsdWUiOnRydWUsInByZWNvbnNlbnQiOnRydWUsImZpcmVkIjpmYWxzZX0seyJjaWQiOjMsImlkIjoiYW5hbHl0aWNzIiwidmFsdWUiOnRydWUsInByZWNvbnNlbnQiOnRydWUsImZpcmVkIjpmYWxzZX0seyJjaWQiOjQsImlkIjoibWFya2V0aW5nIiwidmFsdWUiOnRydWUsInByZWNvbnNlbnQiOnRydWUsImZpcmVkIjpmYWxzZX0seyJjaWQiOjUsImlkIjoidW5jYXRlZ29yaXplZCIsInZhbHVlIjp0cnVlLCJwcmVjb25zZW50Ijp0cnVlLCJmaXJlZCI6ZmFsc2V9XX0="
},
{
"domain": ".semrush.com",
"expirationDate": 1653330779,
"hostOnly": false,
"httpOnly": false,
"name": "PHPSESSID",
"path": "/",
"sameSite": null,
"secure": false,
"session": false,
"storeId": null,
"value": "5fae739e1c04bd53e0277ace79c66a42"
},
{
"domain": ".semrush.com",
"expirationDate": 1653330848.842239,
"hostOnly": false,
"httpOnly": true,
"name": "SSO-JWT",
"path": "/",
"sameSite": null,
"secure": true,
"session": false,
"storeId": null,
"value": "eyJhbGciOiJFUzI1NiIsInR5cCI6IkpXVCJ9.eyJqdGkiOiI1ZmFlNzM5ZTFjMDRiZDUzZTAyNzdhY2U3OWM2NmE0MiIsImlhdCI6MTY1MzI0NDQ0MywiaXNzIjoic3NvIiwidWlkIjoxMTUzMDk5MX0.vRJyjJg-4-BQegKjQelluPjXTt3aWQj-Q6ghcOKhucFYlr_-S2sMM3q_DTW8QMt3qnSxIiKBlIBLey1G6OvsUw"
}
]
